### ISSUE TITLE
Remove WriteAReview button from sidepanel

### ISSUE THREAD

**Issue by Puh00** [Puh00/Bookly#12]
Since it needs a book in the backend. Or simply go straight to chooseABookFragment.kt

**Comment by kusuoki** [comment]
I concur
![14964f68dd22634c628d1b0a5b6f862a](https://user-images.githubusercontent.com/54945977/90756050-30f0ee80-e2dc-11ea-9e49-7658ba56ae06.png)

**Comment by Puh00** [comment]
Removed
